<?php

namespace App\Providers\CarServiceProvider;

use App\Providers\AppServiceProvider;

class CarServiceProvider extends AppServiceProvider
{
    public function register()
    {
        parent::register(); // TODO: Change the autogenerated stub
        $this->app->bind(
            'App\Repository\CarRepository\CarRepositoryInterface',
            'App\Repository\CarRepository\EloquentCarRepository'
        );

        $this->app->bind(
            'App\Repository\CarRepository\CarColorRepositoryInterface',
            'App\Repository\CarRepository\EloquentCarColorRepository'
        );
    }
}
